# Generated by ruby-webyast-0.1 Selenium formatter
# Date: Thu Jul 23 2009 14:05:37 GMT+0200 (CEST)

require "selenium/test_case"

class Login_test < Selenium::TestCase
  
  def test_login_test_credentials
    @selenium.open "/hosts"
    @selenium.click "link=localhost"
    @selenium.wait_for_page_to_load "30000"
    assert @selenium.is_element_present("login")
    assert @selenium.is_element_present("password")
  end

  
  def test_login_test_services_list
    @selenium.open "/hosts"
    assert @selenium.is_element_present("css=div[class~='services-list']")
  end

  
  def test_login_test_guest_login
    @selenium.open "/hosts?error=nohostid"
    @selenium.click "link=localhost"
    @selenium.wait_for_page_to_load "30000"
    @selenium.type "login", "webyast_guest"
    @selenium.type "password", "test"
    @selenium.click "login_button"
    @selenium.wait_for_page_to_load "30000"
    assert !@selenium.is_element_present("Login incorrect")
    @selenium.click "link=Logout"
    @selenium.wait_for_page_to_load "30000"
    assert @selenium.is_text_present("You have been logged out")
  end

  
  def test_login_test_loggedin_hosts
    @selenium.open "/hosts?error=nohostid"
    @selenium.click "link=localhost"
    @selenium.wait_for_page_to_load "30000"
    @selenium.type "login", "webyast_guest"
    @selenium.type "password", "test"
    @selenium.click "login_button"
    @selenium.wait_for_page_to_load "30000"
    assert !@selenium.is_element_present("Login incorrect")
    @selenium.open "/hosts"
    @selenium.wait_for_page_to_load "30000"
    @selenium.click "link=localhost"
    @selenium.wait_for_page_to_load "30000"
    assert !@selenium.is_text_present("This is embarrasing....")
    @selenium.click "link=Logout"
    @selenium.wait_for_page_to_load "30000"
    assert @selenium.is_text_present("You have been logged out")
  end


end
