# Generated by ruby-webyast-0.1 Selenium formatter
# Date: Mon Aug 17 2009 14:00:00 GMT+0200 (CEST)

require "selenium/test_case"

class Permission_test < Selenium::TestCase
  
  def test_permission_test
    @selenium.open "/permissions"
    @selenium.click "link=dummy-host"
    @selenium.wait_for_page_to_load "30000"
    @selenium.type "login", "schubi"
    @selenium.type "password", "tes"
    @selenium.click "login_button"
    @selenium.wait_for_page_to_load "30000"
    @selenium.type "user", "schubi"
    @selenium.click "commit"
    @selenium.wait_for_page_to_load "30000"
    @selenium.click "//div[@id='content']/div[4]/form/form/table/tbody/tr[2]/td[2]/ul/ul/li[9]/div[1]"
    @selenium.click "//div[@id='content']/div[4]/form/form/table/tbody/tr[2]/td[2]/ul/ul/li[9]/ul/li[2]/div[2]"
    @selenium.click "org.opensuse.yast.patch.install"
    @selenium.click "//input[@name='commit' and @value='Set']"
    @selenium.wait_for_page_to_load "30000"
    @selenium.click "//a[contains(@href, '/logout')]"
    @selenium.wait_for_page_to_load "30000"
  end
end
