# Generated by ruby-webyast-0.1 Selenium formatter
# Date: Wed Jul 22 2009 17:00:46 GMT+0200 (CEST)

require "selenium/test_case"

class Systemtime_test < Selenium::TestCase
  
  def test_systemtime_test_login
    @selenium.open "/hosts"
    @selenium.click "link=localhost"
    @selenium.wait_for_page_to_load "30000"
    @selenium.type "login", "webyast_guest"
    @selenium.type "password", "test"
    @selenium.click "login_button"
    @selenium.wait_for_page_to_load "30000"
    assert !@selenium.is_element_present("Enter login credentials")
  end

  
  def test_systemtime_test_lookat
    @selenium.open "/controlpanel"
    @selenium.click "link=Configure Time"
    @selenium.wait_for_page_to_load "30000"
    assert @selenium.is_text_present("exact:Region:")
    assert @selenium.is_text_present("exact:Timezone:")
    assert @selenium.is_text_present("Hardware clock is set to UTC")
  end

  
  def test_systemtime_test_datepicker
    @selenium.open "/systemtime"
    @selenium.click "date_date"
    assert @selenium.is_element_present("xpath=//div[@id=\"ui-datepicker-div\"]")
    assert @selenium.is_element_present("css=div#ui-datepicker-div")
  end


end
