# Generated by ruby-webyast-0.1 Selenium formatter
# Date: Thu Aug 20 2009 14:54:38 GMT+0200 (CEST)

require "selenium/test_case"

class Systemtime_test < Selenium::TestCase
  
  def test_systemtime_test_login
    @selenium.open "/systemtime"
    @selenium.click "link=dummy-host"
    @selenium.wait_for_page_to_load "30000"
    @selenium.type "login", "webyast"
    @selenium.type "password", "test"
    @selenium.click "login_button"
    @selenium.wait_for_page_to_load "30000"
    assert !@selenium.is_element_present("Enter login credentials")
  end

  
  def test_systemtime_test_lookat
    @selenium.open "/systemtime"
    assert @selenium.is_element_present("currenttime")
    assert @selenium.is_element_present("utc")
    @selenium.click "date_date"
    assert @selenium.is_element_present("xpath=//div[@id=\"ui-datepicker-div\"]")
    assert @selenium.is_element_present("css=div#ui-datepicker-div")
    @selenium.click "link=21"
    @selenium.click "//a[contains(@href, '/logout')]"
    @selenium.wait_for_page_to_load "30000"
  end


end
