require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

begin
    require 'tasks/webservice'
rescue LoadError => e
    $stderr.puts "Install rubygem-yast2-webservice-tasks.rpm"
end

desc 'Default: run unit tests.'
task :default => :test

desc 'Test the services plugin.'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

desc 'Generate documentation for this plugin.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.title    = 'Services'
  rdoc.rdoc_dir = 'rdoc'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

desc "Create mo-files for L10n"
task :makemo do
  require 'gettext_rails/tools'
  GetText.create_mofiles
end

desc "Update pot/po files to match new version."
task :updatepo do
  require 'gettext_rails/tools'
  GetText.update_pofiles("yast_webclient_services", Dir.glob("{app,lib}/**/*.{rb,erb,rhtml}"),
                         "yast_webclient services 1.0.0")
end
